---
if: branch !~ ^build-[0-9]*$ AND tag !~ ^build-[0-9]*$ AND branch !~ ^v[0-9]*.[0-9]*.[0-9]*$ AND tag !~ ^v[0-9]*.[0-9]*.[0-9]*$
language: go

# Ubuntu 22.04
os: ["linux"]
dist: jammy

# Go version for Travis (fvt)
go:
- "1.18.5"

git:
    depth: 9999

addons:
  apt:
    update: true
    packages:
    - python3-pip

services:
- docker

before_install:
- sudo pip3 --quiet install yamllint

after_failure:
- echo "Job failed, check the output above"

before_script:
- export REGISTRY_URL=$(echo "${DOCKER_REGISTRY_LIST}" | tr ',' ' ' | cut -d' ' -f1)
- export REGISTRY_REPO=${REGISTRY_URL}/${DOCKER_IMAGE_NAME}

script:
- make deps
- make fvt || travis_terminate 1

deploy:
- provider: script
  script: bash scripts/travis-provider-script.sh
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(release-*)$
