# permissions for end users to view staticroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: staticroute-viewer-role
rules:
- apiGroups:
  - static-route.ibm.com
  resources:
  - staticroutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - static-route.ibm.com
  resources:
  - staticroutes/status
  verbs:
  - get
