# permissions for end users to edit staticroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: staticroute-editor-role
rules:
- apiGroups:
  - static-route.ibm.com
  resources:
  - staticroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - static-route.ibm.com
  resources:
  - staticroutes/status
  verbs:
  - get
